[theme]
primaryColor             = "#0057B8"
backgroundColor          = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#0F1117"
font                     = "sans serif"

[server]
runOnSave = true
